trainer:
  max_steps: 40
  val_check_interval: 50
  check_val_every_n_epoch: 5
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
model:
  class_path: training.linear_semantic.LinearSemantic
  init_args:
    network:
      class_path: models.linear_decoder.LinearDecoder
data:
  class_path: datasets.step2_dataset.step2_data